{
    "id": "sub_1QrHadJyueeXhqQIMdnTmMLV",
    "object": "subscription",
    "application": null,
    "application_fee_percent": null,
    "automatic_tax": {
    "disabled_reason": null,
    "enabled": false,
    "liability": null
    },
    "billing_cycle_anchor": 1739273119,
    "billing_cycle_anchor_config": null,
    "billing_thresholds": null,
    "cancel_at": null,
    "cancel_at_period_end": false,
    "canceled_at": null,
    "cancellation_details": {
    "comment": null,
    "feedback": null,
    "reason": null
    },
    "collection_method": "charge_automatically",
    "created": 1739273119,
    "currency": "eur",
    "current_period_end": 1741692319,
    "current_period_start": 1739273119,
    "customer": "cus_RknABpfyY4zP0I",
    "days_until_due": null,
    "default_payment_method": null,
    "default_source": null,
    "default_tax_rates": [],
    "description": null,
    "discount": null,
    "discounts": [],
    "ended_at": null,
    "invoice_settings": {
    "account_tax_ids": null,
    "issuer": {
    "type": "self"
    }
    },
    "items": {
    "object": "list",
    "data": [
    {
    "id": "si_RknAdwnLFh08zh",
    "object": "subscription_item",
    "billing_thresholds": null,
    "created": 1739273119,
    "discounts": [],
    "metadata": [],
    "plan": {
    "id": "price_1QorkEJyueeXhqQIbKDjOlGW",
    "object": "plan",
    "active": true,
    "aggregate_usage": null,
    "amount": 1000,
    "amount_decimal": "1000",
    "billing_scheme": "per_unit",
    "created": 1738697114,
    "currency": "eur",
    "interval": "month",
    "interval_count": 1,
    "livemode": false,
    "metadata": [],
    "meter": null,
    "nickname": null,
    "product": "prod_RiIKvpqgi3IYfm",
    "tiers_mode": null,
    "transform_usage": null,
    "trial_period_days": null,
    "usage_type": "licensed"
    },
    "price": {
    "id": "price_1QorkEJyueeXhqQIbKDjOlGW",
    "object": "price",
    "active": true,
    "billing_scheme": "per_unit",
    "created": 1738697114,
    "currency": "eur",
    "custom_unit_amount": null,
    "livemode": false,
    "lookup_key": null,
    "metadata": [],
    "nickname": null,
    "product": "prod_RiIKvpqgi3IYfm",
    "recurring": {
    "aggregate_usage": null,
    "interval": "month",
    "interval_count": 1,
    "meter": null,
    "trial_period_days": null,
    "usage_type": "licensed"
    },
    "tax_behavior": "unspecified",
    "tiers_mode": null,
    "transform_quantity": null,
    "type": "recurring",
    "unit_amount": 1000,
    "unit_amount_decimal": "1000"
    },
    "quantity": 1,
    "subscription": "sub_1QrHadJyueeXhqQIMdnTmMLV",
    "tax_rates": []
    }
    ],
    "has_more": false,
    "total_count": 1,
    "url": "\/v1\/subscription_items?subscription=sub_1QrHadJyueeXhqQIMdnTmMLV"
    },
    "latest_invoice": {
    "id": "in_1QrHadJyueeXhqQImtRs0FEv",
    "object": "invoice",
    "account_country": "FR",
    "account_name": "Factory Online",
    "account_tax_ids": null,
    "amount_due": 1000,
    "amount_paid": 1000,
    "amount_remaining": 0,
    "amount_shipping": 0,
    "application": null,
    "application_fee_amount": null,
    "attempt_count": 1,
    "attempted": true,
    "auto_advance": false,
    "automatic_tax": {
    "disabled_reason": null,
    "enabled": false,
    "liability": null,
    "status": null
    },
    "automatically_finalizes_at": null,
    "billing_reason": "subscription_create",
    "charge": "ch_3QrHadJyueeXhqQI1UgxmePJ",
    "collection_method": "charge_automatically",
    "created": 1739273119,
    "currency": "eur",
    "custom_fields": null,
    "customer": "cus_RknABpfyY4zP0I",
    "customer_address": null,
    "customer_email": "client@example.com",
    "customer_name": "Jenny Rosen",
    "customer_phone": null,
    "customer_shipping": null,
    "customer_tax_exempt": "none",
    "customer_tax_ids": [],
    "default_payment_method": null,
    "default_source": null,
    "default_tax_rates": [],
    "description": null,
    "discount": null,
    "discounts": [],
    "due_date": null,
    "effective_at": 1739273119,
    "ending_balance": 0,
    "footer": null,
    "from_invoice": null,
    "hosted_invoice_url":
    "https:\/\/invoice.stripe.com\/i\/acct_1OI9wrJyueeXhqQI\/test_YWNjdF8xT0k5d3JKeXVlZVhocVFJLF9Sa25BMjlNY09TZzFhOUtLS3phelZTM010b2FNcEZoLDEyOTgxMzkyMQ0200r4Ml1CoN?s=ap",
    "invoice_pdf":
    "https:\/\/pay.stripe.com\/invoice\/acct_1OI9wrJyueeXhqQI\/test_YWNjdF8xT0k5d3JKeXVlZVhocVFJLF9Sa25BMjlNY09TZzFhOUtLS3phelZTM010b2FNcEZoLDEyOTgxMzkyMQ0200r4Ml1CoN\/pdf?s=ap",
    "issuer": {
    "type": "self"
    },
    "last_finalization_error": null,
    "latest_revision": null,
    "lines": {
    "object": "list",
    "data": [
    {
    "id": "il_1QrHadJyueeXhqQIoIOXpRhn",
    "object": "line_item",
    "amount": 1000,
    "amount_excluding_tax": 1000,
    "currency": "eur",
    "description": "1 \u00d7 Abonnement Premium (at \u20ac10.00 \/ month)",
    "discount_amounts": [],
    "discountable": true,
    "discounts": [],
    "invoice": "in_1QrHadJyueeXhqQImtRs0FEv",
    "livemode": false,
    "metadata": [],
    "period": {
    "end": 1741692319,
    "start": 1739273119
    },
    "plan": {
    "id": "price_1QorkEJyueeXhqQIbKDjOlGW",
    "object": "plan",
    "active": true,
    "aggregate_usage": null,
    "amount": 1000,
    "amount_decimal": "1000",
    "billing_scheme": "per_unit",
    "created": 1738697114,
    "currency": "eur",
    "interval": "month",
    "interval_count": 1,
    "livemode": false,
    "metadata": [],
    "meter": null,
    "nickname": null,
    "product": "prod_RiIKvpqgi3IYfm",
    "tiers_mode": null,
    "transform_usage": null,
    "trial_period_days": null,
    "usage_type": "licensed"
    },
    "pretax_credit_amounts": [],
    "price": {
    "id": "price_1QorkEJyueeXhqQIbKDjOlGW",
    "object": "price",
    "active": true,
    "billing_scheme": "per_unit",
    "created": 1738697114,
    "currency": "eur",
    "custom_unit_amount": null,
    "livemode": false,
    "lookup_key": null,
    "metadata": [],
    "nickname": null,
    "product": "prod_RiIKvpqgi3IYfm",
    "recurring": {
    "aggregate_usage": null,
    "interval": "month",
    "interval_count": 1,
    "meter": null,
    "trial_period_days": null,
    "usage_type": "licensed"
    },
    "tax_behavior": "unspecified",
    "tiers_mode": null,
    "transform_quantity": null,
    "type": "recurring",
    "unit_amount": 1000,
    "unit_amount_decimal": "1000"
    },
    "proration": false,
    "proration_details": {
    "credited_items": null
    },
    "quantity": 1,
    "subscription": "sub_1QrHadJyueeXhqQIMdnTmMLV",
    "subscription_item": "si_RknAdwnLFh08zh",
    "tax_amounts": [],
    "tax_rates": [],
    "type": "subscription",
    "unit_amount_excluding_tax": "1000"
    }
    ],
    "has_more": false,
    "total_count": 1,
    "url": "\/v1\/invoices\/in_1QrHadJyueeXhqQImtRs0FEv\/lines"
    },
    "livemode": false,
    "metadata": [],
    "next_payment_attempt": null,
    "number": "58564032-0014",
    "on_behalf_of": null,
    "paid": true,
    "paid_out_of_band": false,
    "payment_intent": {
    "id": "pi_3QrHadJyueeXhqQI1fhBj68K",
    "object": "payment_intent",
    "amount": 1000,
    "amount_capturable": 0,
    "amount_details": {
    "tip": []
    },
    "amount_received": 1000,
    "application": null,
    "application_fee_amount": null,
    "automatic_payment_methods": null,
    "canceled_at": null,
    "cancellation_reason": null,
    "capture_method": "automatic",
    "client_secret": "pi_3QrHadJyueeXhqQI1fhBj68K_secret_qfQev3RJYuo63F4FTIw9OGYMs",
    "confirmation_method": "automatic",
    "created": 1739273119,
    "currency": "eur",
    "customer": "cus_RknABpfyY4zP0I",
    "description": "Subscription creation",
    "invoice": "in_1QrHadJyueeXhqQImtRs0FEv",
    "last_payment_error": null,
    "latest_charge": "ch_3QrHadJyueeXhqQI1UgxmePJ",
    "livemode": false,
    "metadata": [],
    "next_action": null,
    "on_behalf_of": null,
    "payment_method": "pm_1QrHaZJyueeXhqQItYPTtteD",
    "payment_method_configuration_details": null,
    "payment_method_options": {
    "card": {
    "installments": null,
    "mandate_options": null,
    "network": null,
    "request_three_d_secure": "automatic"
    },
    "link": {
    "persistent_token": null
    },
    "paypal": {
    "preferred_locale": null,
    "reference": null
    },
    "sepa_debit": []
    },
    "payment_method_types": [
    "card",
    "link",
    "paypal",
    "sepa_debit"
    ],
    "processing": null,
    "receipt_email": null,
    "review": null,
    "setup_future_usage": "off_session",
    "shipping": null,
    "source": null,
    "statement_descriptor": null,
    "statement_descriptor_suffix": null,
    "status": "succeeded",
    "transfer_data": null,
    "transfer_group": null
    },
    "payment_settings": {
    "default_mandate": null,
    "payment_method_options": null,
    "payment_method_types": null
    },
    "period_end": 1739273119,
    "period_start": 1739273119,
    "post_payment_credit_notes_amount": 0,
    "pre_payment_credit_notes_amount": 0,
    "quote": null,
    "receipt_number": null,
    "rendering": null,
    "shipping_cost": null,
    "shipping_details": null,
    "starting_balance": 0,
    "statement_descriptor": null,
    "status": "paid",
    "status_transitions": {
    "finalized_at": 1739273119,
    "marked_uncollectible_at": null,
    "paid_at": 1739273119,
    "voided_at": null
    },
    "subscription": "sub_1QrHadJyueeXhqQIMdnTmMLV",
    "subscription_details": {
    "metadata": []
    },
    "subtotal": 1000,
    "subtotal_excluding_tax": 1000,
    "tax": null,
    "test_clock": null,
    "total": 1000,
    "total_discount_amounts": [],
    "total_excluding_tax": 1000,
    "total_pretax_credit_amounts": [],
    "total_tax_amounts": [],
    "transfer_data": null,
    "webhooks_delivered_at": 1739273119
    },
    "livemode": false,
    "metadata": [],
    "next_pending_invoice_item_invoice": null,
    "on_behalf_of": null,
    "pause_collection": null,
    "payment_settings": {
    "payment_method_options": null,
    "payment_method_types": null,
    "save_default_payment_method": "off"
    },
    "pending_invoice_item_interval": null,
    "pending_setup_intent": null,
    "pending_update": null,
    "plan": {
    "id": "price_1QorkEJyueeXhqQIbKDjOlGW",
    "object": "plan",
    "active": true,
    "aggregate_usage": null,
    "amount": 1000,
    "amount_decimal": "1000",
    "billing_scheme": "per_unit",
    "created": 1738697114,
    "currency": "eur",
    "interval": "month",
    "interval_count": 1,
    "livemode": false,
    "metadata": [],
    "meter": null,
    "nickname": null,
    "product": "prod_RiIKvpqgi3IYfm",
    "tiers_mode": null,
    "transform_usage": null,
    "trial_period_days": null,
    "usage_type": "licensed"
    },
    "quantity": 1,
    "schedule": null,
    "start_date": 1739273119,
    "status": "active",
    "test_clock": null,
    "transfer_data": null,
    "trial_end": null,
    "trial_settings": {
    "end_behavior": {
    "missing_payment_method": "create_invoice"
    }
    },
    "trial_start": null
    }